# version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: go-postgres
    restart: always
    environment:
      POSTGRES_USER: ashish
      POSTGRES_PASSWORD: Ashish@#21
      POSTGRES_DB: mydatabase
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
